import { writeFile } from 'node:fs/promises';
import type {
  CliRuntime,
  RuntimeFactoryOptions,
  RuntimeGenerateArgs,
  RuntimeGenerateResult,
} from '../types.js';

export function createMockRuntime(
  _options: RuntimeFactoryOptions = {},
): CliRuntime {
  return {
    name: 'mock',
    telemetryProvider: 'openai',
    telemetryModel: 'mock-oauth-cli',
    async run(args: RuntimeGenerateArgs): Promise<RuntimeGenerateResult> {
      await writeFile(args.componentPath, mockComponent(args.taskPrompt), 'utf8');
      return {
        status: 'ok',
        componentPath: './Component.tsx',
        notes: ['Generated by mock runtime.'],
      };
    },
  };
}

function mockComponent(taskPrompt: string): string {
  const label = taskPrompt.match(/User request:\n([\s\S]*?)(?:\n\n|$)/)?.[1]
    ?.trim()
    .slice(0, 120) ?? 'Generated UI';
  return `import * as React from 'react';

const rows = [
  ['Runtime', 'mock'],
  ['Status', 'compiled'],
  ['Mode', 'OAuth CLI add-on']
];

export default function Component() {
  return (
    <section style={{
      fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
      maxWidth: 520,
      margin: '0 auto',
      padding: 20,
      color: '#172033',
      background: '#fbfbf8',
      border: '1px solid #d8d3c8',
      borderRadius: 8,
      boxShadow: '0 10px 30px rgba(23, 32, 51, 0.08)'
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'center' }}>
        <div>
          <p style={{ margin: 0, color: '#51606f', fontSize: 12, textTransform: 'uppercase', letterSpacing: 0 }}>
            ggui add-on
          </p>
          <h1 style={{ margin: '6px 0 0', fontSize: 22, lineHeight: 1.2 }}>
            ${escapeForJsxText(label)}
          </h1>
        </div>
        <span style={{
          flex: '0 0 auto',
          padding: '6px 10px',
          borderRadius: 999,
          background: '#dbeafe',
          color: '#1d4ed8',
          fontSize: 12,
          fontWeight: 700
        }}>
          READY
        </span>
      </div>
      <dl style={{ margin: '18px 0 0', display: 'grid', gap: 8 }}>
        {rows.map(([key, value]) => (
          <div key={key} style={{
            display: 'grid',
            gridTemplateColumns: '120px 1fr',
            gap: 12,
            padding: '10px 0',
            borderTop: '1px solid #e7e2d7'
          }}>
            <dt style={{ color: '#667085', fontSize: 13 }}>{key}</dt>
            <dd style={{ margin: 0, color: '#172033', fontSize: 13, fontWeight: 650 }}>{value}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
}
`;
}

function escapeForJsxText(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/{/g, '&#123;')
    .replace(/}/g, '&#125;');
}
